apiVersion: v1
kind: Pod
metadata:
  name: exemplo-grupo3
  namespace: laboratorio
  labels:
    owner: grupo3
    env: aula
spec:
  automountServiceAccountToken: false
  containers:
    - name: app
      image: nginxinc/nginx-unprivileged:1.28-alpine
      securityContext:
        privileged: false
        runAsNonRoot: true
        runAsUser: 101
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop: [ALL]
        seccompProfile:
          type: RuntimeDefault
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 250m
          memory: 128Mi
